name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 2 * * *' # Every night at 2:30am UTC (if you change this schedule, also change the if statement in the test steps)

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        path: encr.dev

    - name: Set up Node
      uses: actions/setup-node@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - id: go-cache-paths
      run: |
        echo "::set-output name=go-build::$(go env GOCACHE)"
        echo "::set-output name=go-mod::$(go env GOMODCACHE)"

    - name: Install encore-go
      run: curl --fail -L -o encore-go.tar.gz https://github.com/encoredev/go/releases/download/encore-go1.20.2/linux_x86-64.tar.gz && tar -C . -xzf ./encore-go.tar.gz

    - name: Go Build Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

    - name: Go Mod Cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

    - name: Build dashapp
      run: cd encr.dev/cli/daemon/dash/dashapp && npm install && node node_modules/esbuild/install.js && npm test && npm run build

    - name: Build
      run: cd encr.dev && go build ./...

    # If we're not running on a schedule, we only want to run tests on changed code
    - name: Run tests on changed code
      run: cd encr.dev && go test -short -tags=dev_build ./...
      if: github.event.schedule != '30 2 * * *'
      env:
        ENCORE_GOROOT: ${{ github.workspace }}/encore-go
        ENCORE_RUNTIME_PATH: ${{ github.workspace }}/encr.dev/runtime

    # Each night we want to run all tests multiple times to catch any flaky tests
    # We will shuffle the order in which tests are run and run them 25 times looking
    # for failures. We will also fail fast so that we don't waste time running tests
    # that are already failing.
    - name: Run all tests multiple times
      run:  cd encr.dev && go test -v --count=25 -failfast -shuffle=on -tags=dev_build ./...
      if:   github.event.schedule == '30 2 * * *'
      env:
        ENCORE_GOROOT: ${{ github.workspace }}/encore-go
        ENCORE_RUNTIME_PATH: ${{ github.workspace }}/encr.dev/runtime

    - name: Build for Windows
      run: cd encr.dev && go build ./...
      env:
        GOOS: windows

    - name: Report Nightly Failure
      uses: ravsamhq/notify-slack-action@v2
      if: ${{ failure() && github.event.schedule == '30 2 * * *' }}
      with:
        status: ${{ job.status }} # required
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }} # required
